#' Dataset: polymer_crystallization
#'
#' Simulated dataset representing the crystallized fraction of a polymer
#' as a function of time. This dataset is provided for examples and tests in the package.
#'
#' @format A data.frame with 60 rows and 2 variables:
#' \describe{
#'   \item{t}{Time (arbitrary units).}
#'   \item{Y}{Transformed fraction (values between 0 and 1).}
#' }
#' @source Generated by `data-raw/make_data.R` (simulation).
"polymere_cristallisation"
